services:
  redis:
    image: redis:7-alpine
    container_name: inferrust-redis
    ports:
      - "6379:6379"
    restart: always

  ollama:
    image: ollama/ollama:latest
    container_name: inferrust-ollama
    # Removemos o "ports" daqui para evitar conflito na porta 11434 do host!
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  proxy:
    build: .
    container_name: inferrust-proxy
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - REDIS_URL=redis://redis:6379
      - BACKEND_URLS=http://ollama:11434
      - RATE_LIMIT_BURST=${RATE_LIMIT_BURST:-100000}
      - RATE_LIMIT_RPS=${RATE_LIMIT_RPS:-100000}
    depends_on:
      - redis
      - ollama
    restart: always

volumes:
  ollama_data: